name: MPC LIB CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  gofmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # tag: v4
      - name: Check Source Formatting
        run: |
          INCORRECTLY_FORMATTED_FILES=$(gofmt -l $GITHUB_WORKSPACE)
          if [ ${#INCORRECTLY_FORMATTED_FILES} -gt 0 ]; then
            echo "Please run \`make fmt\` and update the PR"
            echo
            echo "incorrectly formatted files:"
            echo ${INCORRECTLY_FORMATTED_FILES//$GITHUB_WORKSPACE/} | tr ' ' '\n'
            exit 1
          else
            echo "all files are formatted correctly"
          fi

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # tag: v4
      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # tag: v5
        with:
          go-version: '1.20'
      - name: Download dependencies
        run: go mod download
      - name: Run tests
        run: go test -v ./...

  docker-test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # tag: v3
    - name: Get Docker Image Data
      id: docker-image-data
      env:
        PR_NUMBER: ${{ github.event.number }}
        IMAGE_NAME: ${{ github.event.repository.name }}-test
      run: |
        echo "name=$IMAGE_NAME" >> $GITHUB_OUTPUT
        echo "tag=pull-request-$PR_NUMBER" >> $GITHUB_OUTPUT
    